In [28]:
import gym
import numpy as np
import random

env = gym.make("FrozenLake-v0")
env.reset()
#env.render()

0

In [29]:
print("Action space: ", env.action_space)
print("Observation space: ", env.observation_space)

Action space:  Discrete(4)
Observation space:  Discrete(16)


In [30]:
def learn(env, alpha = 0.1, gamma = 0.4, epsilon = 0.2, game_numbers = 1000):
  q_table = np.zeros((16,4))
  for i in range(game_numbers):
    state = env.reset()
    done = False
    while not done:
     if epsilon > random.uniform(0,1):
        action = env.action_space.sample()
     else:
       action = np.argmax(q_table[state])
     next_state, reward, done,_ = env.step(action)
     old_value = q_table[state, action]
     next_max = np.max(q_table[next_state])
     new_value = (1 - alpha) * old_value + alpha * (reward + next_max * gamma)
     q_table[state, action] = new_value
  
  return q_table

In [31]:
q_table = learn(env)
print(q_table)

[[1.17171811e-12 1.15958024e-12 1.21750621e-12 1.10737665e-12]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000